#!/bin/bash
# Used:
# nmap -p- --open -T5 -v -n ip -oG allPorts

# Extract nmap information
# Run as:
# extractPorts allPorts

function extractPorts(){
	# spiega come si usa
	if [ -z "$1" ]; then
		echo "Esempio: extractPorts <nomefile>"
		return 1
	fi

	#  file non trovato
	if [ ! -f "$1" ]; then
		echo "File $1 non trovato"
		return 1
	fi

	#if this not found correctly, you can delete it, from "if" to "fi".
	if ! grep -qE '^[^#].*/open/' "$1"; then
		echo "Formato non valido: Usa -oG <file>, in nmap per il corretto formato."
		return 1
	fi

	ports="$(cat $1 | grep -oP '\d{1,5}/open' | awk '{print $1}' FS='/' | xargs | tr ' ' ',')";
	ip_address="$(cat $1 | grep -oP '\d{1,3}\.\d{1,3}\.\d{1,3}\.\d{1,3}' | sort -u | head -n 1)"
	echo -e "\n[*] Estrazione informazioni...\n" > extractPorts.tmp
	echo -e "\t[*] Indirizzo IP: $ip_address"  >> extractPorts.tmp
	echo -e "\t[*] Porte aperte: $ports\n"  >> extractPorts.tmp
	echo $ports | tr -d '\n' | xclip -selection clipboard
	echo -e "[*] Porte copiate nel clipboard (ctrl+shift+v)\n"  >> extractPorts.tmp
	cat extractPorts.tmp; rm extractPorts.tmp
}
extractPorts "$1"
